platform :ios, "8.0"

pod 'AFNetworking'
pod 'MJRefresh', '~> 3.0.7'
pod 'SDWebImage', '~> 3.7.3'
pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
pod 'MJExtension'
pod 'DACircularProgress'
pod 'pop'